/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames

/**
 *
 *
 * @param id
 * @param type
 */


data class AddPatientToDoctorRequest(

    @JsonNames("id")
    val id: kotlin.Long? = null,

    @JsonNames("type")
    val type: kotlin.String? = null

) {


}

