/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames


/**
 * 
 *
 * @param `data` 
 * @param errors 
 * @param meta 
 */


data class BaseResponseDto (

    @JsonNames( "data")
    val `data`: kotlin.collections.List<kotlin.Any>? = null,

    @JsonNames( "errors")
    val errors: kotlin.collections.List<kotlin.Any>? = null,

    @JsonNames( "meta")
    val meta: kotlin.collections.List<kotlin.Any>? = null

) {


}

