/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames


/**
 * 
 *
 * @param ids 
 */


data class ExerciseRequest (

    @JsonNames( "ids")
    val ids: kotlin.collections.List<kotlin.Long>? = null

) {


}

