/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models

import brn.mobile.brnmobile.api.models.ExerciseCreateDto

import kotlinx.serialization.json.JsonNames


/**
 * Request dto for create exercise 'words'
 *
 * @param exerciseName Exercise name
 * @param level Level
 * @param locale Locale
 * @param subGroup Subgroup code
 * @param typeOfExercise type of exercise
 * @param noiseLevel Noise level
 * @param words Words for creating exercise
 * @param noiseUrl Noise url
 */


data class ExerciseWordsCreateDto (

    /* Exercise name */
    @JsonNames( "exerciseName")
    override val exerciseName: kotlin.String,

    /* Level */
    @JsonNames( "level")
    override val level: kotlin.Int,

    /* Locale */
    @JsonNames( "locale")
    override val locale: ExerciseCreateDto.Locale,

    /* Subgroup code */
    @JsonNames( "subGroup")
    override val subGroup: kotlin.String,

    /* type of exercise */
    @JsonNames( "typeOfExercise")
    override val typeOfExercise: ExerciseCreateDto.TypeOfExercise,

    /* Noise level */
    @JsonNames( "noiseLevel")
    val noiseLevel: kotlin.Int,

    /* Words for creating exercise */
    @JsonNames( "words")
    val words: kotlin.collections.List<kotlin.String>,

    /* Noise url */
    @JsonNames( "noiseUrl")
    val noiseUrl: kotlin.String? = null

) : ExerciseCreateDto {

    /**
     * Locale
     *
     * Values: RU,EN,TR
     */

    enum class Locale(val value: kotlin.String) {
        @JsonNames( "RU") RU("RU"),
        @JsonNames( "EN") EN("EN"),
        @JsonNames( "TR") TR("TR");
    }
    /**
     * type of exercise
     *
     * Values: SINGLE_SIMPLE_WORDS,PHRASES,SENTENCE
     */

    enum class TypeOfExercise(val value: kotlin.String) {
        @JsonNames( "SINGLE_SIMPLE_WORDS") SINGLE_SIMPLE_WORDS("SINGLE_SIMPLE_WORDS"),
        @JsonNames( "PHRASES") PHRASES("PHRASES"),
        @JsonNames( "SENTENCE") SENTENCE("SENTENCE");
    }

}

