/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames


/**
 * 
 *
 * @param exerciseName Exercise name
 * @param level Level
 * @param locale Locale
 * @param subGroup Subgroup code
 * @param typeOfExercise type of exercise
 */


interface ExerciseCreateDto {

    /* Exercise name */
    @JsonNames( "exerciseName")
    val exerciseName: kotlin.String
    /* Level */
    @JsonNames( "level")
    val level: kotlin.Int
    /* Locale */
    @JsonNames( "locale")
    val locale: ExerciseCreateDto.Locale
    /* Subgroup code */
    @JsonNames( "subGroup")
    val subGroup: kotlin.String
    /* type of exercise */
    @JsonNames( "typeOfExercise")
    val typeOfExercise: ExerciseCreateDto.TypeOfExercise
    /**
     * Locale
     *
     * Values: RU,EN,TR
     */
   
    enum class Locale(val value: kotlin.String) {
        @JsonNames( "RU") RU("RU"),
        @JsonNames( "EN") EN("EN"),
        @JsonNames( "TR") TR("TR");
    }
    /**
     * type of exercise
     *
     * Values: SINGLE_SIMPLE_WORDS,PHRASES,SENTENCE
     */
   
    enum class TypeOfExercise(val value: kotlin.String) {
        @JsonNames( "SINGLE_SIMPLE_WORDS") SINGLE_SIMPLE_WORDS("SINGLE_SIMPLE_WORDS"),
        @JsonNames( "PHRASES") PHRASES("PHRASES"),
        @JsonNames( "SENTENCE") SENTENCE("SENTENCE");
    }

}

