/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models

import kotlinx.datetime.LocalDateTime
import kotlinx.serialization.json.JsonNames


/**
 *
 *
 * @param endTime
 * @param executionSeconds
 * @param exerciseId
 * @param id
 * @param replaysCount
 * @param startTime
 * @param tasksCount
 * @param wrongAnswers
 */


data class StudyHistoryDto(

    @JsonNames( "endTime")
    val endTime: LocalDateTime? = null,

    @JsonNames( "executionSeconds")
    val executionSeconds: kotlin.Int? = null,

    @JsonNames( "exerciseId")
    val exerciseId: kotlin.Long? = null,

    @JsonNames( "id")
    val id: kotlin.Long? = null,

    @JsonNames( "replaysCount")
    val replaysCount: kotlin.Int? = null,

    @JsonNames( "startTime")
    val startTime: LocalDateTime? = null,

    @JsonNames( "tasksCount")
    val tasksCount: kotlin.Int? = null,

    @JsonNames( "wrongAnswers")
    val wrongAnswers: kotlin.Int? = null

) {


}

