/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames


/**
 * 
 *
 * @param name 
 * @param level 
 * @param code 
 * @param description 
 */


data class SubGroupRequest (

    @JsonNames( "name")
    val name: kotlin.String? = null,

    @JsonNames( "level")
    val level: kotlin.Int? = null,

    @JsonNames( "code")
    val code: kotlin.String? = null,

    @JsonNames( "description")
    val description: kotlin.String? = null

) {


}

