/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames


/**
 * 
 *
 * @param description 
 */


data class UpdateResourceDescriptionRequest (

    @JsonNames( "description")
    val description: kotlin.String? = null

) {


}

