/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package brn.mobile.brnmobile.api.models


import kotlinx.serialization.json.JsonNames


/**
 * 
 *
 * @param avatar 
 * @param bornYear 
 * @param description 
 * @param gender 
 * @param name 
 * @param photo 
 */


data class UserAccountChangeRequest (

    @JsonNames( "avatar")
    val avatar: kotlin.String? = null,

    @JsonNames( "bornYear")
    val bornYear: kotlin.Int? = null,

    @JsonNames( "description")
    val description: kotlin.String? = null,

    @JsonNames( "gender")
    val gender: UserAccountChangeRequest.Gender? = null,

    @JsonNames( "name")
    val name: kotlin.String? = null,

    @JsonNames( "photo")
    val photo: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: MALE,FEMALE
     */

    enum class Gender(val value: kotlin.String) {
        @JsonNames( "MALE") MALE("MALE"),
        @JsonNames( "FEMALE") FEMALE("FEMALE");
    }

}

